export const ABBREVIATION_MAP: Record<string, string> = {
    'neural network': 'nn',
    'neural_network': 'nn',
    'linear': 'lin',
    'feature': 'feat',
    'vectorized': 'vec',
    'vector': 'vec',
    'acceleration': 'accel',
    'accelerate': 'accel',
    'implementation': 'impl',
    'implement': 'impl',
    'utility': 'utils',
    'utilities': 'utils',
    'configuration': 'config',
    'configure': 'config',
    'config': 'config',
    'example': 'demo',
    'evaluation': 'eval',
    'evaluate': 'eval',
    'training': 'train',
    'train': 'train',
    'test': 'test',
    'testing': 'test',
    'validation': 'val',
    'validate': 'val',
    'maximum': 'max',
    'minimum': 'min',
    'number': 'num',
    'information': 'info',
    'application': 'app',
    'database': 'db',
    'image': 'img',
    'temporary': 'tmp',
    'temp': 'tmp',
    'argument': 'arg',
    'arguments': 'args',
    'parameter': 'param',
    'parameters': 'params',
    'object': 'obj',
    'string': 'str',
    'integer': 'int',
    'boolean': 'bool',
    'array': 'arr',
    'dictionary': 'dict',
    'function': 'func',
    'variable': 'var',
    'error': 'err',
    'exception': 'exc',
    'message': 'msg',
    'response': 'resp',
    'request': 'req',
    'library': 'lib',
    'document': 'doc',
    'directory': 'dir',
    'source': 'src',
    'destination': 'dst',
    'input': 'in',
    'output': 'out',
    'reference': 'ref',
    'identifier': 'id',
    'index': 'idx',
    'count': 'cnt',
    'current': 'curr',
    'previous': 'prev',
    'next': 'next',
    'initialize': 'init',
    'initial': 'init',
};

export function applyAbbreviations(text: string): string {
    let result = text.toLowerCase();
    const sortedKeys = Object.keys(ABBREVIATION_MAP).sort((a, b) => b.length - a.length);
    for (const key of sortedKeys) {
        const regex = new RegExp(`\\b${key}\\b`, 'gi');
        result = result.replace(regex, ABBREVIATION_MAP[key]);
    }
    return result;
}
